name: Gudmundur Mar Gunnarsson
permalink: /:categories/:year/:month/:day/:title
url:
  "https://www.gmg.is"
gems: [jekyll-livereload, jekyll-sitemap, jekyll-feed]
collections:
  - lists
  - my-site
tag_page: '/thinking/tags/'
category_page: '/thinking/categories/'
sass:
  sass_dir: _sass
  style: compressed