name: Gudmundur Mar Gunnarsson
markdown: kramdown
kramdown:
  input: GFM
permalink: /thinking/:year/:month/:day/:title
url:
  "https://www.gmg.is"
gems: [jekyll-livereload]
baseurl: /gmg.is
collections:
- lists
tag_page: '/thinking/tags/'
category_page: '/thinking/categories/'
sass:
  sass_dir: _sass
  style: compressed